import Link from "next/link";
import { notFound } from "next/navigation";

const ARTICLES: Record<string, { title: string; category: string; readTime: string; content: string }> = {
  "mastering-svg-performance-and-svgo": {
    title: "Mastering SVG Performance: The Complete SVGO & Optimization Guide",
    category: "Performance & Optimization",
    readTime: "6 min read",
    content: `
      <h2>Why Vector Optimization Matters</h2>
      <p>Scalable Vector Graphics (SVGs) are essential for modern high-resolution web interfaces. However, raw SVG files generated by design applications like Figma, Illustrator, or Sketch often contain bloated metadata, XML declarations, comments, and unused IDs that double or triple the file size.</p>

      <h3>Key Steps to Minify SVGs</h3>
      <ul>
        <li><strong>Strip Metadata:</strong> Remove <code>&lt;metadata&gt;</code>, <code>&lt;title&gt;</code>, and design tool XML namespaces.</li>
        <li><strong>Collapse Paths:</strong> Combine duplicate path d-attribute segments into single compound paths.</li>
        <li><strong>Use Inherited Colors:</strong> Replace fixed fill hex codes with <code>currentColor</code> to allow instant CSS styling.</li>
      </ul>

      <div style="margin: 2rem 0; padding: 1.5rem; background: rgba(99, 102, 241, 0.1); border: 1px solid var(--accent); border-radius: 8px;">
        <h4 style="margin-top:0;">Try the Live Tool</h4>
        <p>Clean, minify, and edit your vector graphics in real time with our interactive workspace:</p>
        <a href="/svg-converter" style="color: var(--accent); font-weight: 700;">Launch SVG Converter & Optimizer &rarr;</a>
      </div>
    `
  },
  "converting-svg-to-react-jsx-tsx": {
    title: "Converting and Optimizing SVGs for React, Next.js & TypeScript",
    category: "React & Next.js",
    readTime: "8 min read",
    content: `
      <h2>Integrating Vector Graphics into React</h2>
      <p>Using raw <code>&lt;img src="icon.svg" /&gt;</code> tags prevents CSS styling and color manipulation. Converting SVGs directly into React functional components allows full TypeScript prop support, dynamic color changes via <code>currentColor</code>, and zero layout shift.</p>

      <h3>Attribute Conversion Rules</h3>
      <p>HTML SVG attributes must be converted to camelCase for React JSX compliance:</p>
      <ul>
        <li><code>stroke-width</code> &rarr; <code>strokeWidth</code></li>
        <li><code>fill-rule</code> &rarr; <code>fillRule</code></li>
        <li><code>class</code> &rarr; <code>className</code></li>
      </ul>

      <div style="margin: 2rem 0; padding: 1.5rem; background: rgba(99, 102, 241, 0.1); border: 1px solid var(--accent); border-radius: 8px;">
        <h4 style="margin-top:0;">Instant Component Exporter</h4>
        <p>Paste any SVG and instantly generate ready-to-use React JSX/TSX or Vue 3 component code:</p>
        <a href="/svg-converter" style="color: var(--accent); font-weight: 700;">Open SVG to JSX Exporter &rarr;</a>
      </div>
    `
  },
  "creating-glassmorphic-and-neon-svg-filters": {
    title: "Designing Next-Gen Glassmorphic & Neon UI Effects with SVG Filters",
    category: "UI & CSS Effects",
    readTime: "7 min read",
    content: `
      <h2>The Power of SVG Filter Primitives</h2>
      <p>SVG filters allow complex graphics processing directly inside the browser. By combining <code>feGaussianBlur</code>, <code>feColorMatrix</code>, and <code>feBlend</code>, you can build glowing neon trails, glassmorphic overlays, and dynamic drop shadows that outperform canvas renders.</p>

      <h3>Designing a Neon Glow Filter</h3>
      <p>Below is an example of an SVG filter that adds an outer neon aura to any vector element:</p>
      <pre style="background: rgba(10,10,15,0.9); padding: 1rem; border-radius: 6px; overflow-x: auto; color: #a5b4fc;"><code>&lt;filter id="neon-glow" x="-50%" y="-50%" width="200%" height="200%"&gt;
  &lt;feGaussianBlur stdDeviation="6" result="blur" /&gt;
  &lt;feMerge&gt;
    &lt;feMergeNode in="blur" /&gt;
    &lt;feMergeNode in="SourceGraphic" /&gt;
  &lt;/feMerge&gt;
&lt;/filter&gt;</code></pre>

      <div style="margin: 2rem 0; padding: 1.5rem; background: rgba(99, 102, 241, 0.1); border: 1px solid var(--accent); border-radius: 8px;">
        <h4 style="margin-top:0;">Build Custom Vector Graphics</h4>
        <p>Edit vector colors, rotation, scale, and stroke effects live on our canvas studio:</p>
        <a href="/svg-editor" style="color: var(--accent); font-weight: 700;">Launch SVG Studio &rarr;</a>
      </div>
    `
  }
};

export async function generateStaticParams() {
  return Object.keys(ARTICLES).map((slug) => ({ slug }));
}

export default async function GuideArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = ARTICLES[slug];

  if (!article) {
    notFound();
  }

  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "2rem 0" }}>
      <div style={{ marginBottom: "1.5rem" }}>
        <Link href="/guides" style={{ color: "var(--accent)", fontSize: "0.9rem", fontWeight: 600 }}>
          &larr; Back to all guides
        </Link>
      </div>

      <article className="glass" style={{ padding: "2.5rem", borderRadius: "12px" }}>
        <span style={{ fontSize: "0.85rem", color: "var(--accent)", fontWeight: 600, textTransform: "uppercase" }}>
          {article.category} * {article.readTime}
        </span>
        <h1 style={{ fontSize: "2.25rem", margin: "0.75rem 0 1.5rem 0", lineHeight: 1.3 }}>{article.title}</h1>
        
        <div 
          style={{ lineHeight: 1.7, color: "rgba(255, 255, 255, 0.85)", fontSize: "1.05rem" }}
          dangerouslySetInnerHTML={{ __html: article.content }} 
        />
      </article>
    </div>
  );
}
