import { GameMode, LeaderboardEntry, ModeConfig, QuestItem, TacticalAbility } from "./types";

export const GAME_MODES: ModeConfig[] = [
  {
    mode: "CAMPAIGN",
    name: "Standard Campaign",
    tagline: "5-Sector Orbital Odyssey",
    description: "Progress through 5 escalating sectors, draft tactical augmentations, and confront the Singularity Maw.",
    icon: "[CAMPAIGN]",
    badge: "CORE",
    startingLaunches: 5,
    modifiers: ["Roguelite Drafting Active", "Boss Finales", "Tech Matrix Enabled"],
  },
  {
    mode: "ENDLESS",
    name: "Endless Overdrive",
    tagline: "Infinite Scaling Waves",
    description: "Battle through infinite escalating bumper waves with dynamic speed multiplication and high-score rankings.",
    icon: "[ENDLESS]",
    badge: "HIGH REWARD",
    startingLaunches: 5,
    modifiers: ["Infinite Sectors", "Escalating Velocity", "Milestone Shard Drops"],
  },
  {
    mode: "BOSS_RUSH",
    name: "Titan Boss Rush",
    tagline: "Sequential Boss Gauntlet",
    description: "Confront Vortex Titan, Solar Hyperion, and Aegis Dreadnought back-to-back with speedrun telemetry.",
    icon: "[BOSS]",
    badge: "SPEEDRUN",
    startingLaunches: 6,
    modifiers: ["Back-to-Back Bosses", "Timed Gauntlet", "2x Boss Shards"],
  },
  {
    mode: "TIME_ATTACK",
    name: "Quantum Blitz (60s)",
    tagline: "60-Second Adrenaline Frenzy",
    description: "Score maximum points before the 60-second timer expires. Probes reload automatically with 3x frenzy scoring.",
    icon: "[BLITZ]",
    badge: "FAST PACED",
    timeLimitSeconds: 60,
    startingLaunches: 99,
    modifiers: ["60s Hard Limit", "Auto-Reload Probes", "3x Point Multiplier"],
  },
  {
    mode: "DAILY_CHALLENGE",
    name: "Daily Seeded Matrix",
    tagline: "Synchronized Global Competition",
    description: "Play today's unique seeded layout with special daily mutator physics. Competes on daily leaderboard.",
    icon: "[DAILY]",
    badge: "GLOBAL",
    startingLaunches: 5,
    modifiers: ["Seeded Hazards", "Equal Tech Base", "Daily Quests Boost"],
  },
  {
    mode: "CUSTOM_SANDBOX",
    name: "Custom Sandbox Arena",
    tagline: "Community & User Levels",
    description: "Play user-designed stages created in the Orbital Sandbox Editor or import level codes.",
    icon: "[SANDBOX]",
    badge: "CREATIVE",
    startingLaunches: 5,
    modifiers: ["Custom Placement", "Custom Bosses", "Shareable Level Codes"],
  },
];

export const INITIAL_TACTICAL_ABILITIES: TacticalAbility[] = [
  {
    id: "EMP_PULSE",
    name: "EMP Flashwave",
    icon: "[EMP]",
    hotkey: "1",
    cooldownSeconds: 15,
    currentCooldown: 0,
    energyCost: 35,
    description: "Disables all laser beams and freezes enemy drones for 4.5 seconds.",
  },
  {
    id: "GRAVITY_ANCHOR",
    name: "Micro Singularity",
    icon: "[VORTEX]",
    hotkey: "2",
    cooldownSeconds: 20,
    currentCooldown: 0,
    energyCost: 50,
    description: "Deploys a temporary gravitational vortex that vacuums in nearby shards and deflects the orb.",
  },
  {
    id: "QUANTUM_CLONE",
    name: "Tri-Phase Split",
    icon: "[CLONE]",
    hotkey: "3",
    cooldownSeconds: 25,
    currentCooldown: 0,
    energyCost: 65,
    description: "Instantly clones the active orb into 3 phased kinetic projectiles with independent bounce vectors.",
  },
];

export const DAILY_QUESTS: QuestItem[] = [
  {
    id: "Q_SUPERNOVA_3",
    title: "Supernova Trigger",
    description: "Activate Supernova Overdrive 3 times in any mode.",
    target: 3,
    progress: 0,
    rewardShards: 350,
    completed: false,
    claimed: false,
    expiresInHours: 24,
  },
  {
    id: "Q_BOUNCES_50",
    title: "Kinetic Resonance",
    description: "Accumulate 50 bumper bounces in a single mission.",
    target: 50,
    progress: 0,
    rewardShards: 450,
    completed: false,
    claimed: false,
    expiresInHours: 24,
  },
  {
    id: "Q_SCORE_10000",
    title: "High Orbit Ace",
    description: "Achieve a mission score of 10,000 or higher.",
    target: 10000,
    progress: 0,
    rewardShards: 600,
    completed: false,
    claimed: false,
    expiresInHours: 24,
  },
  {
    id: "Q_BOSS_SLAYER",
    title: "Titan Annihilation",
    description: "Defeat 2 Sector Bosses in Campaign or Boss Rush.",
    target: 2,
    progress: 0,
    rewardShards: 800,
    completed: false,
    claimed: false,
    expiresInHours: 24,
  },
];

export const SIMULATED_GLOBAL_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, pilotHandle: "VortexDrifter_99", score: 148500, sector: 18, vesselUsed: "Aegis Prime", peakCombo: 42, region: "US", date: "Today" },
  { rank: 2, pilotHandle: "CyberPhantom_X", score: 124200, sector: 15, vesselUsed: "Chrono Phantom", peakCombo: 38, region: "DE", date: "Today" },
  { rank: 3, pilotHandle: "SolarFlare_Pro", score: 98450, sector: 12, vesselUsed: "Solar Eclipse", peakCombo: 31, region: "JP", date: "Today" },
  { rank: 4, pilotHandle: "TitanForge_AU", score: 87100, sector: 11, vesselUsed: "Titan Dreadnought", peakCombo: 29, region: "AU", date: "Today" },
  { rank: 5, pilotHandle: "QuantumSurge", score: 76200, sector: 9, vesselUsed: "Vortex Striker", peakCombo: 26, region: "GB", date: "Today" },
  { rank: 6, pilotHandle: "NeonPilot_88", score: 65400, sector: 8, vesselUsed: "Photon Dart", peakCombo: 22, region: "CA", date: "Today" },
  { rank: 7, pilotHandle: "AegisRider_01", score: 54100, sector: 7, vesselUsed: "Photon Dart", peakCombo: 19, region: "KR", date: "Today" },
  { rank: 8, pilotHandle: "StarGazer_77", score: 48900, sector: 6, vesselUsed: "Photon Dart", peakCombo: 18, region: "FR", date: "Today" },
];
